# -*- coding: utf-8 -*-
"""
Teks bawaan untuk tabel "Teks Situs" di Airtable.

Script build SELALU membaca Airtable lebih dulu. Teks di file ini hanya dipakai
kalau sebuah Key belum ada / masih kosong di Airtable, supaya website tidak
pernah tampil dengan teks yang hilang.

Format: KEY: (Teks ID, Teks EN, Grup, Catatan untuk editor)
Tanda *bintang* di sekitar kata = kata itu diberi stabilo kuning.
"""

DEFAULT_TEXT = {
    # ------------------------------------------------------------------ Menu & Umum
    "nav.solusi": ("Solusi", "Solutions", "Menu & Umum", "Menu atas"),
    "nav.untuk": ("Untuk Siapa", "Who We Help", "Menu & Umum", "Menu atas"),
    "nav.studi": ("Studi Kasus", "Case Studies", "Menu & Umum", "Menu atas"),
    "nav.blog": ("Blog", "Blog", "Menu & Umum", "Menu atas"),
    "nav.tentang": ("Tentang", "About", "Menu & Umum", "Menu atas"),
    "nav.cta": ("Chat WhatsApp", "Chat on WhatsApp", "Menu & Umum", "Tombol di pojok kanan atas. Maks. 20 karakter."),
    "crumb.home": ("Beranda", "Home", "Menu & Umum", "Breadcrumb"),
    "wa.default": ("Halo Kreasi Digital, saya ingin menceritakan masalah bisnis saya.",
                   "Hi Kreasi Digital, I'd like to talk about a problem in my business.",
                   "Menu & Umum", "Pesan WhatsApp yang otomatis terisi dari tombol umum."),
    "link.solusi": ("Lihat solusinya", "See the solution", "Menu & Umum", "Tautan di kartu masalah bisnis"),
    "link.studi": ("Baca studi kasus", "Read the case study", "Menu & Umum", "Tautan di kartu studi kasus"),
    "link.artikel": ("Baca artikel", "Read the article", "Menu & Umum", "Tautan di kartu artikel"),
    "label.studi": ("Studi kasus", "Case study", "Menu & Umum", "Label kecil di kartu"),
    "label.artikel": ("Artikel", "Article", "Menu & Umum", "Label kecil di kartu"),

    # ------------------------------------------------------------------ SEO Beranda
    "home.title": ("Kreasi Digital | Solusi Digital untuk Masalah Bisnis Anda",
                   "Kreasi Digital | Digital Solutions for Your Business Problems",
                   "SEO Beranda", "Judul tab browser & hasil Google. Maks. 60 karakter."),
    "home.meta": ("Order tercecer, stok tak cocok, data anggota berantakan? Kreasi Digital merancang sistem, aplikasi, dan website sesuai masalah bisnis UMKM, yayasan & organisasi.",
                  "Missed orders, stock that never adds up, messy member data? Kreasi Digital designs systems, apps and websites around the real problems of your business.",
                  "SEO Beranda", "Deskripsi di hasil Google. Maks. 155 karakter."),

    # ------------------------------------------------------------------ Beranda - Hero
    "hero.tag": ("Mitra solusi digital untuk usaha Anda", "Your digital solutions partner", "Beranda - Hero", "Label kecil di atas judul"),
    "hero.h1": ("Setiap *masalah bisnis* punya solusinya. Kami bantu merancang dan membangunnya.",
                "Every *business problem* has a solution. We help you design and build it.",
                "Beranda - Hero", "Judul utama (H1). Kata di antara *bintang* diberi stabilo."),
    "hero.sub": ("Sebagai pemilik usaha, pikiran Anda tidak pernah lepas dari masalah bisnis: pekerjaan yang masih manual, data yang tercecer, atau keluhan tim tentang alur kerja. Kreasi Digital hadir untuk mendengarkan masalah bisnis itu, lalu merancang sistem, tools, atau website yang benar-benar menyelesaikannya.",
                 "As a business owner, your mind is never far from business problems: work that's still manual, scattered data, or complaints from your team about how things run. Kreasi Digital listens to those problems, then designs the systems, tools or websites that actually solve them.",
                 "Beranda - Hero", "Paragraf di bawah judul"),
    "hero.cta1": ("Ceritakan Masalah Bisnis Anda", "Tell Us Your Business Problem", "Beranda - Hero", "Tombol utama (ke WhatsApp)"),
    "hero.cta2": ("Lihat Masalah yang Kami Selesaikan", "See the Problems We Solve", "Beranda - Hero", "Tombol kedua (ke halaman Solusi)"),
    "banner.h": ("Ceritakan masalah bisnisnya. Kami rancang solusinya.",
                 "Tell us the problem. We'll design the solution.",
                 "Beranda - Hero", "Brand promise, pita di bawah hero"),
    "banner.p": ("Bagi kami, teknologi bukan untuk membuat pusing, tapi untuk menyelesaikan masalah nyata yang Anda hadapi setiap hari.",
                 "For us, technology isn't meant to add headaches. It's meant to solve the real problems you face every day.",
                 "Beranda - Hero", "Kalimat di bawah brand promise"),

    # ------------------------------------------------------------------ Beranda - Section
    "sec.masalah.tag": ("Apakah ini terdengar familiar?", "Does this sound familiar?", "Beranda - Section", ""),
    "sec.masalah.h2": ("Masalah bisnis yang sering kami dengar dari pemilik usaha dan pengurus organisasi",
                       "Business problems we often hear from owners and organization leaders", "Beranda - Section", ""),
    "sec.masalah.penutup": ("Masalah bisnis Anda tidak ada di daftar ini? Justru itu yang ingin kami dengar.",
                            "Don't see your business problem here? That's exactly what we want to hear.", "Beranda - Section", ""),
    "sec.masalah.cta": ("Ceritakan ke Kami", "Tell Us About It", "Beranda - Section", ""),
    "sec.untuk.tag": ("Untuk siapa", "Who we help", "Beranda - Section", ""),
    "sec.untuk.h2": ("Solusi digital untuk UMKM, yayasan, dan organisasi",
                     "Digital solutions for small businesses, foundations and organizations", "Beranda - Section", ""),
    "sec.proses.tag": ("Cara kami bekerja", "How we work", "Beranda - Section", ""),
    "sec.proses.h2": ("Kami mulai dari masalah bisnis Anda, bukan dari produk kami",
                      "We start with your business problem, not with our product", "Beranda - Section", ""),
    "sec.kenapa.tag": ("Tentang Kreasi Digital", "About Kreasi Digital", "Beranda - Section", ""),
    "sec.kenapa.h2": ("Mitra yang paham cara bisnis benar-benar berjalan",
                      "A partner who understands how business really works", "Beranda - Section", ""),
    "sec.kenapa.p": ("Kami bukan tim yang baru mengenal dunia kerja. Dengan pengalaman puluhan tahun, kami terbiasa menghadapi pemilik usaha, pengurus, dan karyawan dengan cara yang profesional dan beretika. Itu sebabnya kami bertanya dulu sebelum menawarkan apa pun.",
                     "We're not new to the working world. With decades of experience, we're used to working with owners, boards and staff in a professional, ethical way. That's why we ask questions before we offer anything.",
                     "Beranda - Section", ""),
    "sec.kenapa.poin": ("Solusi pas ukuran, tidak menjual yang tidak Anda butuhkan\nKomunikasi jelas dan tepat waktu dari awal sampai selesai\nSistem menjadi milik Anda, bukan sewa yang hilang begitu berhenti",
                        "Right-sized solutions; we never sell what you don't need\nClear, on-time communication from start to finish\nThe system is yours, not a rental that disappears when you stop paying",
                        "Beranda - Section", "Satu poin per baris"),
    "sec.studi.tag": ("Studi kasus", "Case studies", "Beranda - Section", ""),
    "sec.studi.h2": ("Masalah bisnis nyata, solusi nyata", "Real business problems, real solutions", "Beranda - Section", ""),
    "sec.studi.all": ("Lihat semua studi kasus", "See all case studies", "Beranda - Section", ""),
    "cta.h2": ("Masalah bisnis apa yang sedang Anda pikirkan hari ini?",
               "What business problem is on your mind today?", "Beranda - Section", "Ajakan penutup (juga dipakai di halaman lain)"),
    "cta.p": ("Ceritakan saja, tanpa istilah teknis. Kami bantu memetakan solusinya, gratis dan tanpa kewajiban.",
              "Just tell us, no technical terms needed. We'll help map out the solution, free and with no obligation.",
              "Beranda - Section", ""),
    "cta.btn": ("Ceritakan Masalah Bisnis Anda", "Tell Us Your Business Problem", "Beranda - Section", ""),

    # ------------------------------------------------------------------ Halaman Lain
    "solusi.title": ("Masalah Bisnis yang Kami Selesaikan", "Business Problems We Solve", "Halaman Lain", "Title halaman /solusi/"),
    "solusi.meta": ("Daftar masalah bisnis yang sering dialami UMKM, yayasan, dan organisasi, beserta penyebab, tanda-tanda, dan pilihan solusi digitalnya.",
                    "Common business problems faced by small businesses, foundations and organizations, with their causes, warning signs and digital solution options.",
                    "Halaman Lain", ""),
    "solusi.h1": ("Masalah bisnis apa yang ingin Anda selesaikan?", "Which business problem do you want to solve?", "Halaman Lain", ""),
    "solusi.sub": ("Pilih masalah yang paling mirip dengan kondisi usaha Anda. Setiap halaman menjelaskan penyebabnya, tanda-tandanya, dan pilihan solusinya.",
                   "Pick the problem closest to your situation. Each page explains why it happens, the warning signs and your solution options.",
                   "Halaman Lain", ""),
    "solusi.kenapa": ("Kenapa ini terjadi", "Why this happens", "Halaman Lain", "Judul section di halaman solusi"),
    "solusi.tanda": ("Tanda-tanda Anda butuh solusi", "Signs you need a solution", "Halaman Lain", ""),
    "solusi.pilihan": ("Pilihan solusi, dari yang paling sederhana", "Solution options, starting with the simplest", "Halaman Lain", ""),
    "solusi.pilihan_sub": ("Tidak semua masalah butuh sistem besar. Kami bantu memilih langkah yang paling pas.",
                           "Not every problem needs a big system. We help you choose the step that fits.", "Halaman Lain", ""),
    "solusi.bukti": ("Studi kasus terkait", "Related case studies", "Halaman Lain", ""),
    "solusi.artikel": ("Bacaan terkait", "Related reading", "Halaman Lain", ""),
    "solusi.faq": ("Pertanyaan yang sering diajukan", "Frequently asked questions", "Halaman Lain", ""),
    "solusi.cta_h": ("Masalah bisnis Anda mirip seperti ini?", "Facing something similar in your business?", "Halaman Lain", ""),
    "solusi.cta_p": ("Ceritakan kondisinya lewat WhatsApp. Kami bantu memetakan solusinya, gratis dan tanpa kewajiban.",
                     "Tell us about it on WhatsApp. We'll help map out the solution, free and with no obligation.", "Halaman Lain", ""),
    "solusi.cta_btn": ("Diskusikan via WhatsApp", "Discuss on WhatsApp", "Halaman Lain", ""),
    "solusi.lain": ("Masalah bisnis lainnya", "Other business problems", "Halaman Lain", ""),
    "untuk.title": ("Untuk Siapa Kreasi Digital", "Who Kreasi Digital Helps", "Halaman Lain", "Title halaman /untuk/"),
    "untuk.meta": ("Kreasi Digital membantu UMKM, yayasan, dan organisasi menyelesaikan masalah bisnis dengan sistem, aplikasi, dan website yang sesuai cara kerja mereka.",
                   "Kreasi Digital helps small businesses, foundations and organizations solve business problems with systems, apps and websites built around how they work.",
                   "Halaman Lain", ""),
    "untuk.h1": ("Solusi digital untuk setiap jenis usaha dan organisasi", "Digital solutions for every kind of business and organization", "Halaman Lain", ""),
    "untuk.sub": ("Setiap jenis usaha punya masalah bisnisnya sendiri. Pilih yang paling mirip dengan Anda.",
                  "Every kind of organization has its own business problems. Choose the one closest to yours.", "Halaman Lain", ""),
    "untuk.col1": ("Jika Anda mengalami...", "If you're dealing with...", "Halaman Lain", "Kolom kiri tabel di halaman /untuk/"),
    "untuk.col2": ("Solusi yang bisa kami bangun", "What we can build", "Halaman Lain", "Kolom kanan tabel"),
    "untuk.bukti": ("Bukti dari proyek kami", "Proof from our projects", "Halaman Lain", ""),
    "studi.title": ("Studi Kasus Kreasi Digital", "Kreasi Digital Case Studies", "Halaman Lain", "Title halaman /studi-kasus/"),
    "studi.meta": ("Studi kasus Kreasi Digital: masalah bisnis nyata dari UMKM dan organisasi, solusi yang kami bangun, dan hasilnya.",
                   "Kreasi Digital case studies: real business problems from small businesses and organizations, what we built, and the results.",
                   "Halaman Lain", ""),
    "studi.h1": ("Dari masalah bisnis ke solusi nyata", "From business problem to real solution", "Halaman Lain", ""),
    "studi.sub": ("Setiap studi kasus dimulai dari masalah bisnis klien, lalu solusi yang kami rancang dan hasilnya.",
                  "Every case study starts with the client's business problem, then what we designed and what changed.", "Halaman Lain", ""),
    "studi.masalah": ("Masalah bisnis", "The business problem", "Halaman Lain", ""),
    "studi.solusi": ("Solusi dari Kreasi Digital", "What Kreasi Digital built", "Halaman Lain", ""),
    "studi.hasil": ("Hasilnya", "The results", "Halaman Lain", ""),
    "studi.kunjungi": ("Lihat proyeknya", "View the project", "Halaman Lain", ""),
    "studi.terkait": ("Solusi terkait", "Related solutions", "Halaman Lain", ""),
    "studi.cta_h": ("Punya masalah bisnis serupa?", "Facing a similar problem?", "Halaman Lain", ""),
    "blog.title": ("Blog Kreasi Digital | Tips Menyelesaikan Masalah Bisnis", "Kreasi Digital Blog | Practical Tips for Business Problems", "Halaman Lain", "Title halaman /blog/"),
    "blog.meta": ("Tips praktis untuk pemilik usaha dan pengurus organisasi: cara merapikan pesanan, stok, keuangan, data anggota, dan masalah bisnis lainnya.",
                  "Practical tips for owners and organization leaders on tidying up orders, stock, finances, member data and other business problems.",
                  "Halaman Lain", ""),
    "blog.h1": ("Tips praktis menyelesaikan masalah bisnis", "Practical tips for solving business problems", "Halaman Lain", ""),
    "blog.sub": ("Panduan singkat dari pengalaman kami membantu UMKM, yayasan, dan organisasi.",
                 "Short guides drawn from our work with small businesses, foundations and organizations.", "Halaman Lain", ""),
    "blog.terkait": ("Solusi yang dibahas di artikel ini", "Solutions discussed in this article", "Halaman Lain", ""),
    "blog.kembali": ("Artikel lainnya", "More articles", "Halaman Lain", ""),
    "blog.kosong": ("Artikel baru akan segera hadir.", "New articles are coming soon.", "Halaman Lain", ""),
    "nf.title": ("Halaman tidak ditemukan", "Page not found", "Halaman Lain", "Halaman 404"),
    "nf.p": ("Halaman yang Anda cari mungkin sudah dipindahkan. Coba mulai dari daftar masalah bisnis yang kami selesaikan.",
             "The page you're looking for may have moved. Try starting from the list of business problems we solve.",
             "Halaman Lain", ""),
    "nf.btn": ("Lihat daftar masalah bisnis", "See the list of business problems", "Halaman Lain", ""),

    # ------------------------------------------------------------------ Footer
    "footer.text": ("Kreasi Digital adalah mitra solusi digital untuk UMKM, yayasan, dan organisasi. Kami mendengarkan masalah bisnis Anda, lalu merancang sistem, tools, atau website yang pas.",
                    "Kreasi Digital is a digital solutions partner for small businesses, foundations and organizations. We listen to your business problem, then design the system, tool or website that fits.",
                    "Footer", ""),
    "footer.area": ("Area layanan", "Service area", "Footer", "Label sebelum area layanan (isi area ada di tabel Kontak)"),
    "footer.col_solusi": ("Masalah yang Kami Selesaikan", "Problems We Solve", "Footer", ""),
    "footer.col_untuk": ("Untuk Siapa", "Who We Help", "Footer", ""),
    "footer.col_sosmed": ("Ikuti Kami", "Follow Us", "Footer", ""),
    "footer.sosmed_kosong": ("Link sosial media akan segera hadir.", "Social media links coming soon.", "Footer", ""),
    "footer.tagline": ("Dibuat dengan sepenuh hati untuk para pemilik usaha.", "Built with care for hardworking business owners.", "Footer", ""),

    # ------------------------------------------------------------------ Newsletter
    "nl.tag": ("Newsletter", "Newsletter", "Newsletter", ""),
    "nl.h2": ("Tips menyelesaikan masalah bisnis, langsung ke email Anda", "Tips for solving business problems, straight to your inbox", "Newsletter", ""),
    "nl.p": ("Kami kirim artikel dan tips praktis sesekali saja. Tanpa spam.", "We send practical articles and tips only occasionally. No spam.", "Newsletter", ""),
    "nl.placeholder": ("email@usahaanda.com", "you@business.com", "Newsletter", ""),
    "nl.btn": ("Daftar", "Subscribe", "Newsletter", ""),
    "nl.invalid": ("Masukkan alamat email yang valid.", "Please enter a valid email address.", "Newsletter", ""),
    "nl.sending": ("Mendaftarkan...", "Subscribing...", "Newsletter", ""),
    "nl.ok": ("Terima kasih! Email Anda sudah kami catat.", "Thank you! Your email has been added.", "Newsletter", ""),
    "nl.err": ("Maaf, ada kendala koneksi. Silakan coba lagi nanti.", "Sorry, there was a connection problem. Please try again later.", "Newsletter", ""),
}
